name: Owncloud # Name of the Catalog Entry
description: |
  Provides self hosted storage
version: 0.0.1 # Version of the Catalog to be used
category: Storage # Category to be used for searching catalog entries
maintainer: Zenobius Jiricek # The maintainer of the catalog entry
license: MIT # The license
projectURL: https://github.com/airtonix/rancher-catalog # A URL related to the catalog entry