version: '2'
services:
  db:
    image: postgres:9.5
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /database

  web:
    image: concourse/concourse
    command: web
    links:
    - db
    ports:
    - "{{CONCOURSE_SSH_PORT}}:2222"
    expose:
    -  "2222"
    -  "8080"
    volumes:
    - "{{CONCOURSE_STORAGE_PATH}}/web:/concourse-keys"
    environment:
      CONCOURSE_BASIC_AUTH_USERNAME: {{CONCOURSE_BASICAUTH_ADMIN_USERNAME}}
      CONCOURSE_BASIC_AUTH_PASSWORD: {{CONCOURSE_BASICAUTH_ADMIN_PASSWORD}}
      CONCOURSE_EXTERNAL_URL: "{{CONCOURSE_EXTERNAL_URL}}"
      CONCOURSE_POSTGRES_DATA_SOURCE: |-
        postgres://admin:password@db:5432/concourse?sslmode=disable

  worker:
    image: concourse/concourse
    privileged: true
    links:
    - web
    command: worker
    volumes:
    - {{CONCOURSE_STORAGE_PATH}}/worker:/concourse-keys"
    environment:
      CONCOURSE_TSA_HOST: web