version: "2"
services:
  certs:
    image: airtonix/concourse-certs

  db:
    image: postgres:9.5
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: ${CONCOURSE_DB_USERNAME}
      POSTGRES_PASSWORD: ${CONCOURSE_DB_PASSWORD}
      PGDATA: /database

  web:
    image: concourse/concourse
    command: web
    links:
      - db
    ports:
      - "${CONCOURSE_SSH_PORT}:2222"
    expose:
      -  "2222"
      -  "8080"
    volumes_from:
      - certs
    environment:
      CONCOURSE_SESSION_SIGNING_KEY: /concourse-certs/web/session_signing_key
      CONCOURSE_TSA_HOST_KEY: /concourse-certs/web/tsa_host_key
      CONCOURSE_TSA_AUTHORIZED_KEYS: /concourse-certs/web/tsa-authorized-keys
      CONCOURSE_BASIC_AUTH_USERNAME: ${CONCOURSE_BASICAUTH_ADMIN_USERNAME}
      CONCOURSE_BASIC_AUTH_PASSWORD: ${CONCOURSE_BASICAUTH_ADMIN_PASSWORD}
      CONCOURSE_EXTERNAL_URL: "${CONCOURSE_EXTERNAL_URL}"
      CONCOURSE_POSTGRES_DATA_SOURCE: |-
        postgres://${CONCOURSE_DB_USERNAME}:${CONCOURSE_DB_PASSWORD}@db:5432/concourse?sslmode=disable

  worker:
    image: concourse/concourse
    privileged: true
    links:
      - web
    volumes_from:
      - certs
    command: worker
    environment:
      CONCOURSE_TSA_HOST: web
      CONCOURSE_TSA_PUBLIC_KEY: /concourse-certs/worker/tsa_host_key.pub
      CONCOURSE_WORKER_PRIVATE_KEY: /concourse-certs/worker/worker_key
