version: "2"
catalog:
  name: "Concourse"
  version: 0.0.2
  uuid: concourse-airtonix-2
  minimum_rancher_version: v0.51.0
  questions:

    - variable: 'CONCOURSE_EXTERNAL_URL'
      label: 'concourse external hostname'
      description: 'hostname of the concourse instance as seen by fly clients and remote workers'
      required: true
      type: 'string'

    - variable: 'CONCOURSE_STORAGE_PATH'
      label: 'absolute path on rancher host where concours storage is held'
      description: 'For now this just contains keys shared between workers and the tsa.'
      required: true
      type: 'string'

    - variable: 'CONCOURSE_SSH_PORT'
      label: 'external ssh port'
      description: 'For external workers connecting via ssh'
      default: '2222'
      required: true
      type: 'string'

    - variable: 'CONCOURSE_BASICAUTH_ADMIN_USERNAME'
      label: 'admin username'
      default: 'admin'
      required: true
      type: 'string'

    - variable: 'CONCOURSE_BASICAUTH_ADMIN_PASSWORD'
      label: 'admin password'
      default: 'admin'
      required: true
      type: 'string'

    - variable: 'CONCOURSE_DB_USERNAME'
      label: 'database username'
      default: 'concourse'
      required: true
      type: 'string'

    - variable: 'CONCOURSE_DB_PASSWORD'
      label: 'database password'
      default: 'concourse'
      required: true
      type: 'string'

concourse-certs:
  scale: 1
concourse-db:
  scale: 1
concourse-tsa:
  scale: 1
concourse-worker:
  scale: 1
