version: '2'
services:
  db:
    scale: 1
  web:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 8080
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: none
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 60000
  worker:
    scale: 1

.catalog:
  name: # Name of the versioned template of the Catalog Entry
  version: # Version of the versioned template of the Catalog Entry
  description: # Description of the versioned template of the Catalog Entry
  minimum_rancher_version: # The minimum version of Rancher that supports the template, v1.0.1 and 1.0.1 are acceptable inputs
  maximum_rancher_version: # The maximum version of Rancher that supports the template, v1.0.1 and 1.0.1 are acceptable inputs
  upgrade_from: # The previous versions that this template can be upgraded from
  questions:

  - variable: 'CONCOURSE_EXTERNAL_URL'
    label: 'concourse external hostname'
    description: 'hostname of the concourse instance as seen by fly clients and remote workers'
    required: true
    type: 'string'

  - variable: 'CONCOURSE_SSH_PORT'
    label: 'external ssh port'
    description: 'For external workers connecting via ssh'
    default: '2222'
    required: true
    type: 'string'

  - variable: CONCOURSE_BASICAUTH_ADMIN_USERNAME
    label: admin username
    default: admin
    required: true
    type: string

  - variable: CONCOURSE_BASICAUTH_ADMIN_PASSWORD
    label: admin password
    default: admin
    required: true
    type: string

  - variable: CONCOURSE_DB_USERNAME
    label: database username
    default: concourse
    required: true
    type: string

  - variable: CONCOURSE_DB_PASSWORD
    label: database password
    default: concourse
    required: true
    type: string
