resources:
- name: repo
  type: git
  source:
    uri: git@github.com:airtonix/rancher-catalog.git
    branch: master
    private_key: {{github-private-key}}
- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:airtonix/rancher-catalog.git
    initial_version: "0.0.1"
    branch: version
    file: {{IMAGE_NAME}}
    private_key: {{github-private-key}}
- name: hub
  type: docker-image
  source:
    repository: registry.thelma.lan/{{IMAGE_NAME}}
    insecure_registries: ["registry.thelma.lan"]

jobs:
- name: build
  public: true
  serial: true
  plan:
  - get: version
    trigger: true
  - get: repo
    trigger: true
  - put: hub
    params:
      build: repo/dockerfiles/{{IMAGE_NAME}}
      tag: version/{{IMAGE_NAME}}
      tag_as_latest: true

- name: bump
  public: true
  serial: true
  plan:
  - get: version
    passed: [build]
  - put: version
    params:
      file: version/{{IMAGE_NAME}}