resources:
- name: repo
  type: git
  source:
    uri: git@github.com:airtonix/rancher-catalog.git
    branch: master
    private_key: {{github-private-key}}
- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:airtonix/rancher-catalog.git
    initial_version: "0.0.1"
    branch: version
    file: {{semver-version-file}}
    private_key: {{github-private-key}}
- name: hub
  type: docker-image
  source:
    repository: {{docker-repository}}
    insecure_registries: ["registry.thelma.lan"]

jobs:
- name: build
  public: true
  serial: true
  plan:
  - get: repo
    trigger: true
  - get: version
    params:
      bump: patch
      file: {{semver-version-file}}
  - put: hub
    params:
      build: {{hub-docker-file}}
      tag: version/version
      tag_as_latest: true

- name: bump
  public: true
  serial: true
  plan:
  - get: hub
    trigger: true
  - get: version
    passed: [build]
  - put: version
    params:
      bump: patch
