version: "2"
services:

  concourse-certs:
    image: airtonix/concourse-certs:v0.0.9
    command: cat
    stdin_open: true

  concourse-db:
    image: postgres:9.5
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: ${CONCOURSE_DB_USERNAME}
      POSTGRES_PASSWORD: ${CONCOURSE_DB_PASSWORD}
      PGDATA: /database

  concourse-tsa:
    image: concourse/concourse
    command: web
    ports:
      - "${CONCOURSE_SSH_PORT}:2222"
    expose:
      -  "2222"
      -  "8080"
    volumes_from: [concourse-certs]
    labels:
      io.rancher.sidekicks: concourse-certs, concourse-worker
    environment:
      CONCOURSE_BASIC_AUTH_USERNAME: ${CONCOURSE_BASICAUTH_ADMIN_USERNAME}
      CONCOURSE_BASIC_AUTH_PASSWORD: ${CONCOURSE_BASICAUTH_ADMIN_PASSWORD}
      CONCOURSE_EXTERNAL_URL: "${CONCOURSE_EXTERNAL_URL}"
      CONCOURSE_POSTGRES_DATA_SOURCE: postgres://${CONCOURSE_DB_USERNAME}:${CONCOURSE_DB_PASSWORD}@concourse-db:5432/concourse?sslmode=disable

  concourse-worker:
    image: concourse/concourse
    privileged: true
    volumes_from: [concourse-certs]
    command: worker
