name: Concourse (Insecure)
description: |
  Container based continous integration and delivery.

  **Testing Only**
  Only use this template for testing, since it uses a container that
  generates worker and tsa keys which are shared to both tsa and workers.

version: 0.0.1
category: Continous Integration
maintainer: Zenobius Jiricek
license: MIT
projectURL: https://github.com/airtonix/rancher-catalog # A URL related to the catalog entry
